[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_attendance_deposit = "G8PAMHAVZVAzcsKAXVtuJ69msx9tB1tNYKRPoSCtZ54G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
